const en = {
  "2003": "HELLO",
  "2018": "Please accept with term & condition",
  "2008": "Sing Up",
  "4001": "DATA PROBLEM !!!",
  "4002": "NONE AUTHORIZED !!!",
  "4003": "INVALID TOKEN !!!",
  "4004": "Please logout from your old device",
  "4005": "Expire token please login again",
  "4006": "New version is available please update your app",
  "4007": "Please login to continue it",
  "4008": "Payment required",
  "4009": "Invalid parameter",
  "4010": "Account suspended",
  "4011": "You already submit your task.",
  "4100": "Invalid phone number",
  "4101": "Last name is required",
  "4102": "First name is required",
  "4200": "Last name or first name can not contain special character",
  "4201": "Last name or first name can not more then 50 characters",
  "4103": "Password require at less 6 characters",
  "4104": "Confirm Password must be same as pssword",
  "4105": "Phone already register",
  "4108": "Please input phone number and password",
  "4109": "Phone number and password not correct",
  "4171": "Province & School are required",
  "4172":
      "You already make request change, \nYour request on the way pending.\n Please waiting our administrator response.\n Thank your!",
  "4173":
      "You request are blocked, \n due you had been got 3 request denies,\n Please contact our administrator for more info.\n Thank your!",
  "unknown": "Unknown",
  "my_qr": "My QR",
  "study_and_sharing": "Study & Sharing",
  "report": "Report",
  "me_and_privacy": "Me & Privacy",
  "e_school": "E-School Cambodia",
  "my_course": "My Course",
  "my_zoom": "My Zoom",
  "my_library": "My Library",
  "favorite": "Favorite",
  "friend": "Friend",
  "document": "Document",
  "gallery": "Gallery",
  "certificate": "Certificate",
  "summary": "Summary",
  "watch_video": "Watch Video",
  "read_book": "Read Book",
  "relative": "Relative",
  "profile": "Profile",
  "change_password": "Change Password",
  "parent": "Parent",
  "Insurance": "Insurance",
  "invoice": "Invoice",
  "other": "Other",
  "logout": "Logout",
  "hot_chat": "Hot Chat",
  "policy": "Policy",
  "help": "Help",
  "about": "About",
  "share_app": "Share App",
  "dark_mode": "Dark Mode",
  "language": "Language",
  "home": "Home",
  "video": "Video",
  "library": "Library",
  "parthner": "Parthner",
  "zoom": "Zoom",
};
